module lp_constants

export COMMAND_LINE_OPTION_FILENAME,
    COMMAND_LINE_OPTION_USE_NO_PRESOLVE,
    COMMAND_LINE_OPTION_USE_SIMPLEX_METHOD,
    COMMAND_LINE_OPTION_USE_INTERIOR_POINT_METHOD,
    COMMAND_LINE_OPTION_MINIMIZE_OBJECTIVE,
    COMMAND_LINE_OPTION_MAXIMIZE_OBJECTIVE,
    COMMAND_LINE_OPTION_VERBOSE
export OPTION_FILENAME,
    OPTION_USE_SIMPLEX_METHOD,
    OPTION_USE_NO_PRESOLVE,
    OPTION_USE_INTERIOR_POINT_METHOD,
    OPTION_MINIMIZE_OBJECTIVE,
    OPTION_MAXIMIZE_OBJECTIVE,
    OPTION_VERBOSE

const COMMAND_LINE_OPTION_FILENAME = "filename"
const COMMAND_LINE_OPTION_USE_NO_PRESOLVE = "no_presolve"
# const COMMAND_LINE_OPTION_USE_SPARSE_MATRIX = "sparse"
const COMMAND_LINE_OPTION_USE_SIMPLEX_METHOD = "simplex"
const COMMAND_LINE_OPTION_USE_INTERIOR_POINT_METHOD = "interior"
const COMMAND_LINE_OPTION_MINIMIZE_OBJECTIVE = "min"
const COMMAND_LINE_OPTION_MAXIMIZE_OBJECTIVE = "max"
const COMMAND_LINE_OPTION_VERBOSE = "verbose"

const OPTION_FILENAME = "filename"
const OPTION_USE_SIMPLEX_METHOD = "simplex"
const OPTION_USE_NO_PRESOLVE = "use_no_presolve"
# const OPTION_USE_SPARSE_MATRIX = "use_sparse_matrix"
const OPTION_USE_INTERIOR_POINT_METHOD = "ipm"
const OPTION_MINIMIZE_OBJECTIVE = "minimize"
const OPTION_MAXIMIZE_OBJECTIVE = "maximize"
const OPTION_VERBOSE = "verbose"

end # module
